### ISSUE TITLE
kobart_summary.zip의 압축 해제가 되지 않습니다.

### ISSUE THREAD

**Issue by ttaerrim** [EugeneYoo/kobart_summarization_model#1]
지원되는 포맷이 아니라며 압축 해제할 수 없다고 뜨는데 파일을 받아 볼 수 있는 다른 방법이 있을까요?

**Comment by EugeneYoo** [comment]
> 지원되는 포맷이 아니라며 압축 해제할 수 없다고 뜨는데 파일을 받아 볼 수 있는 다른 방법이 있을까요?

파일을 한 번  확인해보겠습니다.

월요일 저녁에 가능할 것 같습니다!

**Comment by EugeneYoo** [comment]
> 지원되는 포맷이 아니라며 압축 해제할 수 없다고 뜨는데 파일을 받아 볼 수 있는 다른 방법이 있을까요?

현재 확인해보니 github bandwidth가 초과되서 lfs로 올린 파일이 비활성화 된 것 같습니다.

요금을 결재하거나 다른 방향으로 공유를 드려야 할 것 같은데, 다른 대안을 찾아보겠습니다.

**Comment by ttaerrim** [comment]
메일이나 구글 드라이브로 공유 가능하다면 그렇게 받을 수 있을까요? 혹시나 하여 메일 남기고 갑니다 ^^ 
ttrrr121@gmail.com

**Comment by EugeneYoo** [comment]
> 메일이나 구글 드라이브로 공유 가능하다면 그렇게 받을 수 있을까요? 혹시나 하여 메일 남기고 갑니다 ^^
> [ttrrr121@gmail.com](mailto:ttrrr121@gmail.com)

최근에 일이 많아서 늦었습니다. 보내드렸습니다. 감사합니다.

**Comment by Onion-Lab** [comment]
저도 메일로 공유 부탁드려도 될까요??
bilv12@naver.com 입니다 :)
