### ISSUE TITLE
kobart_summary.zip 부탁드리고 싶습니다.

### ISSUE THREAD

**Issue by Kim-kwan-woo** [EugeneYoo/kobart_summarization_model#2]
안녕하세요 요즘 kobart를 학습하고 있는 학생입니다.
저도 이번에 학습을 하면서 fine tuning된 모델을 테스트 해보고 싶은데
현재 레포지토리에 있는 zip 파일이 압축해제가 안되서 혹시 가능하시면
메일로 보내주실 수 있나요??

kw2577@naver.com

**Comment by EugeneYoo** [comment]
> 안녕하세요 요즘 kobart를 학습하고 있는 학생입니다. 저도 이번에 학습을 하면서 fine tuning된 모델을 테스트 해보고 싶은데 현재 레포지토리에 있는 zip 파일이 압축해제가 안되서 혹시 가능하시면 메일로 보내주실 수 있나요??
> 
> [kw2577@naver.com](mailto:kw2577@naver.com)

메일 확인해주세요 issue close 하겠습니다.
